DISK_INFO_ENDPOINT = "/"
RESOURCES_ENDPOINT = "/resources"
TRASH_ENDPOINT = "/trash/resources"
RECOVER_ENDPOINT = "/trash/resources/restore"
UPLOAD_ENDPOINT = "/resources/upload"
COPY_ENDPOINT = "/resources/copy"
DOWNLOAD_ENDPOINT = "/resources/download"
FILES_LIST_ENDPOINT = "/resources/files"
