DISK_INFO_ENDPOINT = "/v1/disk"
RESOURCES_ENDPOINT = "/v1/disk/resources"
TRASH_ENDPOINT = "/v1/disk/trash/resources"
RECOVER_ENDPOINT = "/v1/disk/trash/resources/restore"
UPLOAD_ENDPOINT = "/v1/disk/resources/upload"
COPY_ENDPOINT = "/v1/disk/resources/copy"
DOWNLOAD_ENDPOINT = "/v1/disk/resources/download"
FILES_LIST_ENDPOINT = "/v1/disk/resources/files"
